services:
  - type: web
    name: retailshop
    runtime: node
    rootDir: server
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_CONNECT_STRING
        sync: false