ALTER SESSION SET CONTAINER = FREEPDB1;
DECLARE
   user_exists NUMBER;
BEGIN
   SELECT COUNT(*) INTO user_exists FROM dba_users WHERE username = 'RETAIL_STORE';
   IF user_exists > 0 THEN
      EXECUTE IMMEDIATE 'DROP USER RETAIL_STORE CASCADE';
   END IF;
END;
/

CREATE USER RETAIL_STORE IDENTIFIED BY "RetailPass23c#";
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO RETAIL_STORE;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO RETAIL_STORE;

-- Create synonyms or copy tables to RETAIL_STORE schema
GRANT SELECT, INSERT, UPDATE, DELETE ON CATEGORIES TO RETAIL_STORE;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRODUCTS TO RETAIL_STORE;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRODUCT_IMAGES TO RETAIL_STORE;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRODUCT_REVIEWS TO RETAIL_STORE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USERS TO RETAIL_STORE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CARTS TO RETAIL_STORE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CART_ITEMS TO RETAIL_STORE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ORDERS TO RETAIL_STORE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ORDER_ITEMS TO RETAIL_STORE;

-- Also create synonyms so RETAIL_STORE can query without SYS prefix
CREATE OR REPLACE PUBLIC SYNONYM CATEGORIES FOR SYS.CATEGORIES;
CREATE OR REPLACE PUBLIC SYNONYM PRODUCTS FOR SYS.PRODUCTS;
CREATE OR REPLACE PUBLIC SYNONYM PRODUCT_IMAGES FOR SYS.PRODUCT_IMAGES;
CREATE OR REPLACE PUBLIC SYNONYM PRODUCT_REVIEWS FOR SYS.PRODUCT_REVIEWS;
CREATE OR REPLACE PUBLIC SYNONYM USERS FOR SYS.USERS;
CREATE OR REPLACE PUBLIC SYNONYM CARTS FOR SYS.CARTS;
CREATE OR REPLACE PUBLIC SYNONYM CART_ITEMS FOR SYS.CART_ITEMS;
CREATE OR REPLACE PUBLIC SYNONYM ORDERS FOR SYS.ORDERS;
CREATE OR REPLACE PUBLIC SYNONYM ORDER_ITEMS FOR SYS.ORDER_ITEMS;

EXIT;
