-- =========================================================
-- Amazon E-Commerce Database Schema for Oracle Database 23c
-- Target PDB: FREEPDB1
-- Schema: RETAIL_STORE
-- =========================================================

-- Drop existing tables if re-running
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CART_ITEMS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CARTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ORDER_ITEMS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ORDERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PRODUCT_REVIEWS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PRODUCT_IMAGES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PRODUCTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CATEGORIES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- 1. USERS Table
CREATE TABLE USERS (
    USER_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FULL_NAME VARCHAR2(150) NOT NULL,
    EMAIL VARCHAR2(150) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    PHONE VARCHAR2(30),
    ADDRESS VARCHAR2(400),
    CITY VARCHAR2(100),
    POSTAL_CODE VARCHAR2(20),
    ROLE VARCHAR2(20) DEFAULT 'CUSTOMER' CHECK (ROLE IN ('CUSTOMER', 'ADMIN')),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. CATEGORIES Table
CREATE TABLE CATEGORIES (
    CATEGORY_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    SLUG VARCHAR2(100) UNIQUE NOT NULL,
    ICON VARCHAR2(50),
    DESCRIPTION VARCHAR2(500),
    PARENT_ID NUMBER REFERENCES CATEGORIES(CATEGORY_ID) ON DELETE SET NULL
);

-- 3. PRODUCTS Table
CREATE TABLE PRODUCTS (
    PRODUCT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE VARCHAR2(255) NOT NULL,
    DESCRIPTION VARCHAR2(4000),
    BRAND VARCHAR2(100),
    PRICE NUMBER(10, 2) NOT NULL,
    LIST_PRICE NUMBER(10, 2),
    DISCOUNT_PCT NUMBER(5, 2) DEFAULT 0,
    RATING NUMBER(3, 2) DEFAULT 4.5,
    REVIEW_COUNT NUMBER DEFAULT 0,
    STOCK_QTY NUMBER DEFAULT 50,
    MAIN_IMAGE VARCHAR2(1000),
    CATEGORY_ID NUMBER REFERENCES CATEGORIES(CATEGORY_ID) ON DELETE SET NULL,
    IS_PRIME NUMBER(1) DEFAULT 1 CHECK (IS_PRIME IN (0, 1)),
    IS_DEAL NUMBER(1) DEFAULT 0 CHECK (IS_DEAL IN (0, 1)),
    BADGE_TEXT VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. PRODUCT IMAGES Gallery Table
CREATE TABLE PRODUCT_IMAGES (
    IMAGE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRODUCT_ID NUMBER REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE CASCADE,
    IMAGE_URL VARCHAR2(1000) NOT NULL,
    DISPLAY_ORDER NUMBER DEFAULT 1
);

-- 5. PRODUCT REVIEWS Table
CREATE TABLE PRODUCT_REVIEWS (
    REVIEW_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRODUCT_ID NUMBER REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE CASCADE,
    USER_NAME VARCHAR2(100) NOT NULL,
    RATING NUMBER(2, 1) CHECK (RATING BETWEEN 1 AND 5),
    REVIEW_TITLE VARCHAR2(200),
    COMMENT_TEXT VARCHAR2(2000),
    REVIEW_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6. CARTS & CART_ITEMS Table
CREATE TABLE CARTS (
    CART_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    SESSION_TOKEN VARCHAR2(100) UNIQUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CART_ITEMS (
    ITEM_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CART_ID NUMBER REFERENCES CARTS(CART_ID) ON DELETE CASCADE,
    PRODUCT_ID NUMBER REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE CASCADE,
    QUANTITY NUMBER DEFAULT 1 CHECK (QUANTITY > 0),
    ADDED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UK_CART_PRODUCT UNIQUE (CART_ID, PRODUCT_ID)
);

-- 7. ORDERS & ORDER_ITEMS Table
CREATE TABLE ORDERS (
    ORDER_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ORDER_NUMBER VARCHAR2(50) UNIQUE NOT NULL,
    USER_ID NUMBER REFERENCES USERS(USER_ID) ON DELETE SET NULL,
    CUSTOMER_NAME VARCHAR2(150) NOT NULL,
    SHIPPING_ADDRESS VARCHAR2(400) NOT NULL,
    CITY VARCHAR2(100) NOT NULL,
    POSTAL_CODE VARCHAR2(20) NOT NULL,
    PHONE VARCHAR2(30),
    TOTAL_AMOUNT NUMBER(10, 2) NOT NULL,
    PAYMENT_METHOD VARCHAR2(50) DEFAULT 'Card',
    PAYMENT_STATUS VARCHAR2(30) DEFAULT 'Paid',
    ORDER_STATUS VARCHAR2(30) DEFAULT 'Processing' CHECK (ORDER_STATUS IN ('Processing', 'Shipped', 'Out for Delivery', 'Delivered', 'Cancelled')),
    ESTIMATED_DELIVERY TIMESTAMP,
    ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ORDER_ITEMS (
    ORDER_ITEM_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ORDER_ID NUMBER REFERENCES ORDERS(ORDER_ID) ON DELETE CASCADE,
    PRODUCT_ID NUMBER REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE SET NULL,
    PRODUCT_TITLE VARCHAR2(255) NOT NULL,
    PRICE NUMBER(10, 2) NOT NULL,
    QUANTITY NUMBER NOT NULL,
    IMAGE_URL VARCHAR2(1000)
);

-- Indexes for optimal query performance
CREATE INDEX IX_PRODUCTS_CATEGORY ON PRODUCTS(CATEGORY_ID);
CREATE INDEX IX_PRODUCTS_SEARCH ON PRODUCTS(TITLE, BRAND);
CREATE INDEX IX_ORDERS_USER ON ORDERS(USER_ID);
CREATE INDEX IX_REVIEWS_PRODUCT ON PRODUCT_REVIEWS(PRODUCT_ID);

COMMIT;
