ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER USER RETAIL_STORE ACCOUNT UNLOCK;
ALTER USER RETAIL_STORE IDENTIFIED BY "RetailPass23c#";
ALTER PROFILE DEFAULT LIMIT FAILED_LOGIN_ATTEMPTS UNLIMITED;
EXIT;
